name: Daily Post to X

on:
  schedule:
    - cron: "30 13 * * *"  # Every day at 8:30 AM US Central
  workflow_dispatch:       # Allow manual runs too

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the bot
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        run: |
          echo "API_KEY=$API_KEY" > .env
          echo "API_SECRET=$API_SECRET" >> .env
          echo "ACCESS_TOKEN=$ACCESS_TOKEN" >> .env
          echo "ACCESS_TOKEN_SECRET=$ACCESS_TOKEN_SECRET" >> .env
          python rss_to_tweet.py

      - name: Commit posted_links.json
        if: success()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add posted_links.json
          git commit -m "Update posted_links.json after tweet"
          git push
